import { Link } from "react-router-dom";
import { ArrowLeft, Mail, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const Terms = () => (
  <div className="min-h-screen bg-background text-foreground flex flex-col">
    <Header />
    <main className="flex-1">
      <div className="container max-w-4xl py-16 md:py-24 px-6">
        <Button
          variant="ghost"
          asChild
          className="mb-8 -ml-2 text-muted-foreground hover:text-foreground"
        >
          <Link to="/">
            <ArrowLeft className="mr-2 h-4 w-4" /> Back to Home
          </Link>
        </Button>

        <div className="space-y-12 text-muted-foreground leading-relaxed">
          <div className="space-y-4">
            <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-foreground">
              Terms of Service
            </h1>
            <p className="text-sm text-muted-foreground">
              Effective Date: July 4, 2026
            </p>
            <p className="text-sm">
              These Terms of Service ("Terms") are a legal agreement between you
              and{" "}
              <strong className="text-foreground">Americascom, Inc.</strong>{" "}
              (doing business as{" "}
              <strong className="text-foreground">SONGSS Intelligence</strong>)
              governing your access to and use of the SONGSS Intelligence
              website, applications, reports, and related services
              (collectively, the "Service"). By accessing or using the Service,
              you agree to be bound by these Terms. If you do not agree, do not
              use the Service.
            </p>
          </div>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              1. Nature of Service
            </h2>
            <p>
              SONGSS Intelligence provides an{" "}
              <strong className="text-foreground">
                AI-driven music analytics platform
              </strong>{" "}
              that aggregates, analyzes, and presents music-related data from
              public streaming and social sources. Reports, dashboards, charts,
              recommendations, and any other outputs generated by the Service
              are provided for{" "}
              <strong className="text-foreground">
                informational purposes only
              </strong>
              . They do not constitute professional, legal, financial, or
              managerial advice. You are solely responsible for any decisions
              or actions you take based on information provided through the
              Service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              2. No Guarantee of Success
            </h2>
            <p>
              Americascom, Inc. does not guarantee any specific results from
              using the Service, including but not limited to career outcomes,
              playlist placements, streaming growth, social-media growth,
              follower increases, chart positions, or revenue increases. The
              music industry involves many factors outside our control, and
              past or predicted performance metrics shown in the Service are
              not indicative of future results.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              3. No Refunds
            </h2>
            <p>
              Due to the{" "}
              <strong className="text-foreground">
                digital and instantaneous nature
              </strong>{" "}
              of our reports and analytics outputs, all sales and subscription
              charges are final once a report has been generated or a billing
              period has begun. We do not provide refunds for generated reports,
              used subscription periods, or partially used services unless
              required by applicable law.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              4. Data Accuracy
            </h2>
            <p>
              Our insights, reports, and analytics are based on{" "}
              <strong className="text-foreground">
                public streaming and social metrics
              </strong>{" "}
              obtained from third-party platforms and data providers. While we
              strive to provide accurate and timely information, Americascom,
              Inc. is{" "}
              <strong className="text-foreground">
                not responsible for inaccuracies, delays, omissions, or
                changes
              </strong>{" "}
              in third-party data. Platform APIs, metrics, and availability may
              change without notice, which can affect the data shown in the
              Service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              5. AI Services
            </h2>
            <p>
              Reports and insights are generated by the{" "}
              <strong className="text-foreground">
                Songss Neural Intelligence Engine™ (SNIE™)
              </strong>
              , a proprietary AI system owned and operated by Americascom, Inc.
              SNIE™ may use machine-learning models, natural-language processing,
              and third-party AI services to analyze data and produce summaries.
              Outputs are generated automatically and may contain errors or
              incomplete information. You should review all outputs before
              relying on them.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              6. Acceptable Use
            </h2>
            <p>
              You agree to use the Service only for lawful purposes and in
              compliance with these Terms. You may not:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                Misuse, interfere with, or disrupt the Service or its underlying
                infrastructure;
              </li>
              <li>
                Reverse engineer, decompile, scrape, copy, or extract the source
                code, models, algorithms, or data of the Service;
              </li>
              <li>
                Resell, redistribute, license, or commercially exploit reports
                or data obtained through the Service without our prior written
                consent;
              </li>
              <li>
                Use automated tools, bots, or scripts to access or interact
                with the Service in ways that violate these Terms;
              </li>
              <li>
                Impersonate another person or misrepresent your affiliation with
                an artist, label, or rights holder;
              </li>
              <li>
                Use the Service to infringe intellectual property rights,
                violate privacy, or breach any applicable law.
              </li>
            </ul>
            <p>
              We reserve the right to suspend or terminate your account and
              access to the Service for any violation of this Acceptable Use
              policy.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              7. Intellectual Property
            </h2>
            <p>
              All software, technology, designs, logos, trademarks, reports,
              analytics methodologies, and content provided through the Service
              are owned by or licensed to{" "}
              <strong className="text-foreground">Americascom, Inc.</strong> The
              Songss Neural Intelligence Engine™ and SONGSS Intelligence
              branding are proprietary assets of Americascom, Inc.
            </p>
            <p>
              Reports and outputs generated for you are provided for{" "}
              <strong className="text-foreground">subscriber use only</strong>{" "}
              during the term of your active account or subscription. You may
              download and share reports internally for your own business
              purposes, but you may not resell, sublicense, publicly republish,
              or otherwise commercially exploit them without our written
              permission.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              8. Account Registration and Security
            </h2>
            <p>
              To access certain features, you may be required to create an
              account. You are responsible for maintaining the confidentiality
              of your account credentials and for all activity that occurs
              under your account. You agree to notify us immediately of any
              unauthorized use or security breach.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              9. Privacy
            </h2>
            <p>
              Your use of the Service is also governed by our{" "}
              <Link to="/privacy" className="text-primary hover:underline">
                Privacy Policy
              </Link>
              , which explains how we collect, use, and protect your personal
              information.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              10. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, Americascom, Inc. and its
              officers, directors, employees, and agents will not be liable for
              any indirect, incidental, special, consequential, or punitive
              damages, or for any loss of profits, revenue, data, or goodwill
              arising out of or related to your use of the Service, even if
              advised of the possibility of such damages.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              11. Governing Law
            </h2>
            <p>
              These Terms and any dispute arising out of or relating to your
              use of the Service shall be governed by and construed in
              accordance with the laws of the{" "}
              <strong className="text-foreground">
                State of Delaware, United States
              </strong>
              , without regard to its conflict of law principles. You agree that
              any legal action or proceeding relating to these Terms or the
              Service shall be brought exclusively in the state or federal
              courts located in Delaware.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              12. Changes to These Terms
            </h2>
            <p>
              We may modify these Terms from time to time. If we make material
              changes, we will update the effective date and notify you where
              required by law. Your continued use of the Service after any changes
              constitutes your acceptance of the revised Terms.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-foreground">
              13. Contact Us
            </h2>
            <p>
              If you have any questions about these Terms, please contact us:
            </p>
            <div className="flex flex-col sm:flex-row gap-6 pt-2">
              <div className="flex items-start gap-3">
                <Mail className="w-5 h-5 text-primary mt-0.5 shrink-0" />
                <div>
                  <p className="text-foreground font-medium">Email</p>
                  <a
                    href="mailto:hello@songssintelligence.com"
                    className="text-primary hover:underline"
                  >
                    hello@songssintelligence.com
                  </a>
                </div>
              </div>
              <div className="flex items-start gap-3">
                <MapPin className="w-5 h-5 text-primary mt-0.5 shrink-0" />
                <div>
                  <p className="text-foreground font-medium">Mailing Address</p>
                  <p>Americascom, Inc.</p>
                  <p>651 N Broad St, Ste 206</p>
                  <p>Middletown, DE 19709, USA</p>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </main>
    <Footer />
  </div>
);

export default Terms;
