import { Sparkles } from "lucide-react";

const CuratorPitchInsight = () => {
  return (
    <div className="bg-primary/5 border border-primary/20 rounded-xl p-6">
      <div className="flex items-center gap-2 mb-3">
        <Sparkles className="w-4 h-4 text-primary" />
        <span className="text-xs uppercase tracking-widest text-primary font-semibold">
          Smart Insight — Curator Pitch
        </span>
      </div>
      <p className="text-sm text-foreground/90 leading-relaxed italic">
        "Based on your 30-day performance: your audience grew 18% across DSPs with
        strong retention in the 18–34 demographic. Engagement peaks on Fridays.
        Recommended positioning: <span className="text-primary font-medium not-italic">emerging crossover artist
        with viral momentum</span> — ideal for editorial playlist consideration and
        mid-tier festival bookings."
      </p>
      <p className="text-[10px] text-muted-foreground mt-3 uppercase tracking-wider">
        Generated by Songss Neural Intelligence Engine
      </p>
    </div>
  );
};

export default CuratorPitchInsight;
